# ========================================================================
# Cloudflare Pages / Workers Configuration for Ronald 3D
# ========================================================================

name = "dj-ronald-3d"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# Cloudflare D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "ronald3d-db"
database_id = "65f9bbef-f3c5-436e-a81b-21b16c8295bd"
